import { cp } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { describe, expect, it, vi } from "vitest"
import { withEnv } from "../../../tests-integration/helpers/env.ts"
import {
  readTextFile,
  withTempDir,
  writeFileTree
} from "../../../tests-integration/helpers/fs.ts"

const suiClientMocks = vi.hoisted(() => ({
  createSuiClient: vi.fn()
}))

vi.mock("../../src/sui-client.ts", () => ({
  createSuiClient: suiClientMocks.createSuiClient
}))

import {
  deriveFaucetUrl,
  getRpcSnapshot,
  isFaucetSupportedNetwork,
  prepareMoveSourcesForLocalnetTests,
  probeRpcHealth,
  resolveLocalnetConfigDir
} from "../../src/localnet.ts"

describe("tooling localnet helpers", () => {
  it("resolves localnet config dirs with overrides and defaults", async () => {
    const homeDir = os.homedir()

    expect(resolveLocalnetConfigDir("~/sui")).toBe(
      path.resolve(path.join(homeDir, "sui"))
    )

    await withEnv(
      {
        SUI_LOCALNET_CONFIG_DIR: "/tmp/sui-localnet"
      },
      () => {
        expect(resolveLocalnetConfigDir()).toBe(
          path.resolve("/tmp/sui-localnet")
        )
      }
    )

    await withEnv(
      {
        SUI_LOCALNET_CONFIG_DIR: undefined,
        SUI_CONFIG_DIR: undefined
      },
      () => {
        expect(resolveLocalnetConfigDir()).toBe(
          path.resolve(path.join(homeDir, ".sui", "localnet"))
        )
      }
    )
  })

  it("detects faucet-supported networks", () => {
    expect(isFaucetSupportedNetwork("localnet")).toBe(true)
    expect(isFaucetSupportedNetwork("devnet")).toBe(true)
    expect(isFaucetSupportedNetwork("testnet")).toBe(true)
    expect(isFaucetSupportedNetwork("mainnet")).toBe(false)
  })

  it("derives a faucet url from a localnet rpc url", () => {
    expect(deriveFaucetUrl("http://localhost:9000")).toBe(
      "http://localhost:9123/v2/gas"
    )
  })

  it("falls back to default faucet url on invalid rpc url", () => {
    expect(deriveFaucetUrl("not a url")).toBe("http://127.0.0.1:9123/v2/gas")
  })

  it("returns rpc snapshots when the node is healthy", async () => {
    suiClientMocks.createSuiClient.mockReturnValue({
      getLatestSuiSystemState: vi.fn().mockResolvedValue({
        epoch: "1",
        protocolVersion: "1",
        activeValidators: [],
        epochStartTimestampMs: undefined
      }),
      getLatestCheckpointSequenceNumber: vi.fn().mockResolvedValue("10"),
      getReferenceGasPrice: vi.fn().mockResolvedValue(1000n)
    })

    const snapshot = await getRpcSnapshot("http://localhost:9000")
    expect(snapshot.rpcUrl).toBe("http://localhost:9000")
    expect(snapshot.epoch).toBe("1")
  })

  it("reports offline status when rpc snapshot fails", async () => {
    suiClientMocks.createSuiClient.mockReturnValue({
      getLatestSuiSystemState: vi.fn().mockRejectedValue(new Error("down"))
    })

    const result = await probeRpcHealth("http://localhost:9000")
    expect(result.status).toBe("offline")
  })

  it("rewrites staged Move.lock local sources for external dependencies", async () => {
    await withTempDir(async (tempDir) => {
      const workspaceRoot = path.join(tempDir, "workspace")
      const sourceMoveRoot = path.join(
        workspaceRoot,
        "packages",
        "dapp",
        "contracts"
      )
      const destinationMoveRoot = path.join(tempDir, "staged", "contracts")

      await writeFileTree(workspaceRoot, {
        "packages/dapp/contracts/prop-amm/Move.toml": `[package]\nname = "openzeppelin_market_maker"\n\n[dep-replacements.test-publish]\ndeepbook = { local = "../../../../vendor/deepbookv3/packages/deepbook", override = true }\n`,
        "packages/dapp/contracts/prop-amm/Move.lock": `# Generated by move; do not edit\n\n[move]\nversion = 4\n\n[pinned.test-publish.deepbook]\nsource = { local = "../../../../vendor/deepbookv3/packages/deepbook" }\nuse_environment = "test-publish"\nmanifest_digest = "abc"\ndeps = { token = "token" }\n\n[pinned.test-publish.token]\nsource = { local = "../../../../vendor/deepbookv3/packages/token" }\nuse_environment = "test-publish"\nmanifest_digest = "def"\ndeps = {}\n`,
        "vendor/deepbookv3/packages/deepbook/Move.toml": `[package]\nname = "deepbook"\n\n[dependencies]\ntoken = { local = "../token" }\n`,
        "vendor/deepbookv3/packages/token/Move.toml": `[package]\nname = "token"\n`
      })

      await cp(sourceMoveRoot, destinationMoveRoot, { recursive: true })

      await prepareMoveSourcesForLocalnetTests({
        destinationMoveRoot,
        sourceMoveRoot,
        workspaceRoot
      })

      const stagedMoveToml = await readTextFile(
        path.join(destinationMoveRoot, "prop-amm", "Move.toml")
      )
      const stagedMoveLock = await readTextFile(
        path.join(destinationMoveRoot, "prop-amm", "Move.lock")
      )

      expect(stagedMoveToml).toContain(
        '../__external__/vendor/deepbookv3/packages/deepbook'
      )
      expect(stagedMoveLock).toContain(
        'source = { local = "../__external__/vendor/deepbookv3/packages/deepbook" }'
      )
      expect(stagedMoveLock).toContain(
        'source = { local = "../__external__/vendor/deepbookv3/packages/token" }'
      )
    })
  })
})
