[package]
name = "openzeppelin_market_maker"
edition = "2024"
version = "1.0.0-rc.0"

[dependencies]
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "b0c3f8b42f5209205dc3f2802b9312e59518a692" }

[dep-replacements.testnet]
deepbook = { published-at = "0x22be4cade64bf2d02412c7e8d0e8beea2f78828b948118d46735315409371a3c", original-id = "0xfb28c4cbc6865bd1c897d26aecbe1f8792d1509a20ffec692c800660cbec6982" }

[dep-replacements.mainnet]
deepbook = { published-at = "0x337f4f4f6567fcd778d5454f27c16c70e2f274cc6377ea6249ddf491482ef497", original-id = "0x2c8d603bc51326b8c13cef9dd07031a408a48dddb541963357661df5d3204809" }

[dependencies.pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-testnet"

[dep-replacements.test-publish]
pyth = { local = "../pyth-mock", override = true, addr_substitutions = { pyth = "0x2" } }

[environments]
test-publish = "8051a268"
