[package]
name = "prop_amm"
edition = "2024"
version = "1.0.0-rc.0"

[dependencies]
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "b0c3f8b42f5209205dc3f2802b9312e59518a692" }

[environments]
test-publish = "8051a268"
